### ISSUE TITLE
BUG StylingStyle::populateDefaults() saves value of first array element rather than key

### ISSUE THREAD

**Issue by muskie9** [fractaslabs/silverstripe-elemental-stylings#7]
**Example**
```yml
My\Element\Class:
    styles:
      default: 'My Default Style'
      cta: 'My CTA Style'
```

When creating a new `My\Element\Class` the value in the `Style` database field will be `My Default Class` rather than `default`.
